//next import
import Head from "next/head";
import Image from "next/image";

//fonts

//components
import Banner from "../components/Banner/Banner";
import CategorySection from "../components/Category/CategorySection";
import Sale from "../components/Sale/Sale";

export default function Home(props) {
  const test = (file) => {};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <section>
        <Banner />
        <CategorySection />
        <Sale />
      </section>
    </>
  );
}
