//next import
<<<<<<< Updated upstream
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner/Banner";
import Sale from "../components/Sale/Sale";
=======
import Head from 'next/head';
import Image from 'next/image';
>>>>>>> Stashed changes

//fonts

//components
import Banner from '../components/Banner/Banner';
import CategorySection from '../components/Category/CategorySection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <section>
        <Banner />
<<<<<<< Updated upstream
        <Sale />
=======
        <CategorySection />
>>>>>>> Stashed changes
      </section>
    </>
  );
}
